version: "3"

services:
  nginx_brotli:
    image: fholzer/nginx-brotli
    container_name: rsa-client
    ports:
      - "3012:80"
    volumes:
      - "./docker/brotli/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./docker/brotli/custom.conf:/etc/nginx/custom.conf:ro"
      - "./dist:/etc/nginx/html:ro"
